# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FArray(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFArray(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FArray()
    x.Init(buf, n + offset)
    return x

  # FArray
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FArray
  def Array(self, j):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      a = self._tab.Vector(o)
      return self._tab.Get(flatbuffers.number_types.Float32Flags,
                           a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
    return 0

  # FArray
  def ArrayAsNumpy(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
    return 0

  # FArray
  def ArrayLength(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.VectorLen(o)
    return 0

  # FArray
  def Ranges(self, j):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      x = self._tab.Vector(o)
      x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FArray
  def RangesLength(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      return self._tab.VectorLen(o)
    return 0


def FArrayStart(builder): builder.StartObject(2)


def FArrayAddArray(builder, array): builder.PrependUOffsetTRelativeSlot(0,
                                                                        flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                          array), 0)


def FArrayStartArrayVector(builder, numElems): return builder.StartVector(4, numElems, 4)


def FArrayAddRanges(builder, ranges): builder.PrependUOffsetTRelativeSlot(1,
                                                                          flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                            ranges), 0)


def FArrayStartRangesVector(builder, numElems): return builder.StartVector(12, numElems, 4)


def FArrayEnd(builder): return builder.EndObject()
