# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSActor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSActor(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSActor()
        x.Init(buf, n + offset)
        return x

    # FBSActor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSActor
    def ActorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # FBSActor
    def Motors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBSMotor import FBSMotor
            obj = FBSMotor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBSActor
    def MotorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def FBSActorStart(builder): builder.StartObject(2)
def FBSActorAddActorName(builder, actorName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(actorName), 0)
def FBSActorAddMotors(builder, motors): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(motors), 0)
def FBSActorStartMotorsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBSActorEnd(builder): return builder.EndObject()
