# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSBody(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSBody(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSBody()
        x.Init(buf, n + offset)
        return x

    # FBSBody
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSBody
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .FBSVector3 import FBSVector3
            obj = FBSVector3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBSBody
    def AngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .FBSVector3 import FBSVector3
            obj = FBSVector3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FBSBodyStart(builder): builder.StartObject(2)
def FBSBodyAddVelocity(builder, velocity): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)
def FBSBodyAddAngularVelocity(builder, angularVelocity): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(angularVelocity), 0)
def FBSBodyEnd(builder): return builder.EndObject()
