# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers

class FBSBodyObservation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSBodyObservation(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSBodyObservation()
        x.Init(buf, n + offset)
        return x

    # FBSBodyObservation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSBodyObservation
    def Body(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .FBSBody import FBSBody
            obj = FBSBody()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FBSBodyObservationStart(builder): builder.StartObject(1)
def FBSBodyObservationAddBody(builder, body): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(body), 0)
def FBSBodyObservationEnd(builder): return builder.EndObject()
