# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSByteArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSByteArray(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSByteArray()
        x.Init(buf, n + offset)
        return x

    # FBSByteArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSByteArray
    def ByteArray(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # FBSByteArray
    def ByteArrayAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # FBSByteArray
    def ByteArrayLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBSByteArray
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def FBSByteArrayStart(builder): builder.StartObject(2)
def FBSByteArrayAddByteArray(builder, byteArray): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(byteArray), 0)
def FBSByteArrayStartByteArrayVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def FBSByteArrayAddDataType(builder, dataType): builder.PrependUint8Slot(1, dataType, 0)
def FBSByteArrayEnd(builder): return builder.EndObject()
