# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSBody(object):
    __slots__ = ['_tab']

    # FBSBody
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSBody
    def Velocity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # FBSBody
    def AngularVelocity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateFBSBody(builder, velocity_x, velocity_y, velocity_z, angular_velocity_x, angular_velocity_y, angular_velocity_z):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(angular_velocity_z)
    builder.PrependFloat32(angular_velocity_y)
    builder.PrependFloat32(angular_velocity_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(velocity_z)
    builder.PrependFloat32(velocity_y)
    builder.PrependFloat32(velocity_x)
    return builder.Offset()
