# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers


class FBSConfiguration(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFBSConfiguration(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FBSConfiguration()
    x.Init(buf, n + offset)
    return x

  # FBSConfiguration
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FBSConfiguration
  def ConfigurableName(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.String(o + self._tab.Pos)
    return bytes()

  # FBSConfiguration
  def ConfigurableValue(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
    return 0.0


def FBSConfigurationStart(builder): builder.StartObject(2)


def FBSConfigurationAddConfigurableName(builder, configurableName): builder.PrependUOffsetTRelativeSlot(0,
                                                                                                        flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                                          configurableName),
                                                                                                        0)


def FBSConfigurationAddConfigurableValue(builder, configurableValue): builder.PrependFloat64Slot(1,
                                                                                                 configurableValue,
                                                                                                 0.0)


def FBSConfigurationEnd(builder): return builder.EndObject()
