# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class FBSConfigurations(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSConfigurations(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSConfigurations()
        x.Init(buf, n + offset)
        return x

    # FBSConfigurations
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSConfigurations
    def Configurations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBSConfiguration import FBSConfiguration
            obj = FBSConfiguration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBSConfigurations
    def ConfigurationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def FBSConfigurationsStart(builder): builder.StartObject(1)
def FBSConfigurationsAddConfigurations(builder, configurations): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(configurations), 0)
def FBSConfigurationsStartConfigurationsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBSConfigurationsEnd(builder): return builder.EndObject()
