# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSInputRange(object):
    __slots__ = ['_tab']

    # FBSInputRange
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSInputRange
    def DecimalGranularity(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # FBSInputRange
    def MaxInputValue(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # FBSInputRange
    def MinInputValue(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateFBSInputRange(builder, decimalGranularity, maxInputValue, minInputValue):
    builder.Prep(4, 12)
    builder.PrependFloat32(minInputValue)
    builder.PrependFloat32(maxInputValue)
    builder.PrependInt32(decimalGranularity)
    return builder.Offset()
