# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class FBSMotions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSMotions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSMotions()
        x.Init(buf, n + offset)
        return x

    # FBSMotions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSMotions
    def Motions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBSMotion import FBSMotion
            obj = FBSMotion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBSMotions
    def MotionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def FBSMotionsStart(builder): builder.StartObject(1)
def FBSMotionsAddMotions(builder, motions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(motions), 0)
def FBSMotionsStartMotionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBSMotionsEnd(builder): return builder.EndObject()
