# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSNumeral(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSNumeral(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSNumeral()
        x.Init(buf, n + offset)
        return x

    # FBSNumeral
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSNumeral
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FBSNumeralStart(builder): builder.StartObject(1)
def FBSNumeralAddValue(builder, value): builder.PrependFloat32Slot(0, value, 0.0)
def FBSNumeralEnd(builder): return builder.EndObject()
