# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

class FBSObserverData(object):
    NONE = 0
    FBSByteArray = 1
    FBSNumeral = 2
    FBSString = 3
    FBSPosition = 4
    FBSRotation = 5
    FBSEulerTransform = 6
    FBSQuaternionTransform = 7
    FBSBody = 8

