# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSObserver(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSObserver(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSObserver()
        x.Init(buf, n + offset)
        return x

    # FBSObserver
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSObserver
    def ObserverName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # FBSObserver
    def ObservationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBSObserver
    def Observation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def FBSObserverStart(builder): builder.StartObject(3)
def FBSObserverAddObserverName(builder, observerName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(observerName), 0)
def FBSObserverAddObservationType(builder, observationType): builder.PrependUint8Slot(1, observationType, 0)
def FBSObserverAddObservation(builder, observation): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(observation), 0)
def FBSObserverEnd(builder): return builder.EndObject()
