# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

class FBSObserverData(object):
    NONE = 0
    FBSByteArray = 1
    FBSNumeral = 2
    FBSString = 3
    FBSEulerTransform = 4
    FBSQuaternionTransform = 5
    FBSBody = 6

