# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class FBSReaction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBSReaction(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBSReaction()
        x.Init(buf, n + offset)
        return x

    # FBSReaction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSReaction
    def EnvironmentName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # FBSReaction
    def Motions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBSMotion import FBSMotion
            obj = FBSMotion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBSReaction
    def MotionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBSReaction
    def Configurations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBSConfiguration import FBSConfiguration
            obj = FBSConfiguration()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBSReaction
    def ConfigurationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBSReaction
    def Reset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
        return 0

def FBSReactionStart(builder): builder.StartObject(4)
def FBSReactionAddEnvironmentName(builder, environmentName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(environmentName), 0)
def FBSReactionAddMotions(builder, motions): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(motions), 0)
def FBSReactionStartMotionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBSReactionAddConfigurations(builder, configurations): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(configurations), 0)
def FBSReactionStartConfigurationsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBSReactionAddReset(builder, reset): builder.PrependBoolSlot(3, reset, 0)
def FBSReactionEnd(builder): return builder.EndObject()
