# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class FBSReactionParameters(object):
    __slots__ = ['_tab']

    # FBSReactionParameters
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSReactionParameters
    def Interruptible(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # FBSReactionParameters
    def Step(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # FBSReactionParameters
    def Reset(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # FBSReactionParameters
    def Configure(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))
    # FBSReactionParameters
    def Describe(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateFBSReactionParameters(builder, interruptible, step, reset, configure, describe):
    builder.Prep(1, 5)
    builder.PrependBool(describe)
    builder.PrependBool(configure)
    builder.PrependBool(reset)
    builder.PrependBool(step)
    builder.PrependBool(interruptible)
    return builder.Offset()
