# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FBSTransform(object):
    __slots__ = ['_tab']

    # FBSTransform
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBSTransform
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # FBSTransform
    def Rotation(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj

    # FBSTransform
    def Direction(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj


def CreateFBSTransform(builder, position_x, position_y, position_z, rotation_x, rotation_y, rotation_z, direction_x, direction_y, direction_z):
    builder.Prep(4, 36)
    builder.Prep(4, 12)
    builder.PrependFloat32(direction_z)
    builder.PrependFloat32(direction_y)
    builder.PrependFloat32(direction_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(rotation_z)
    builder.PrependFloat32(rotation_y)
    builder.PrependFloat32(rotation_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(position_z)
    builder.PrependFloat32(position_y)
    builder.PrependFloat32(position_x)
    return builder.Offset()
