# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

class FDisplayableValue(object):
  NONE = 0
  FValue = 1
  FValues = 2
  FVector3s = 3
  FValuedVector3s = 4
  FString = 5
  FByteArray = 6
