# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FDouble(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFDouble(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FDouble()
    x.Init(buf, n + offset)
    return x

  # FDouble
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FDouble
  def Vec2(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      x = o + self._tab.Pos
      from .FVector2 import FVector2
      obj = FVector2()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FDouble
  def XRange(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      x = o + self._tab.Pos
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FDouble
  def YRange(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      x = o + self._tab.Pos
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None


def FDoubleStart(builder): builder.StartObject(3)


def FDoubleAddVec2(builder, vec2): builder.PrependStructSlot(0,
                                                             flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                 vec2), 0)


def FDoubleAddXRange(builder, xRange): builder.PrependStructSlot(1,
                                                                 flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                     xRange), 0)


def FDoubleAddYRange(builder, yRange): builder.PrependStructSlot(2,
                                                                 flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                     yRange), 0)


def FDoubleEnd(builder): return builder.EndObject()
