# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

# noinspection PyUnresolvedReferences
import flatbuffers


class FOBS(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFOBS(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FOBS()
    x.Init(buf, n + offset)
    return x

  # FOBS
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FOBS
  def ObservationName(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.String(o + self._tab.Pos)
    return bytes()

  # FOBS
  def ObservationType(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
    return 0

  # FOBS
  def Observation(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      # noinspection PyUnresolvedReferences
      from flatbuffers.table import Table
      obj = Table(bytearray(), 0)
      self._tab.Union(obj, o)
      return obj
    return None


def FOBSStart(builder): builder.StartObject(3)


def FOBSAddObservationName(builder, observationName): builder.PrependUOffsetTRelativeSlot(0,
                                                                                          flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                              observationName),
                                                                                          0)


def FOBSAddObservationType(builder, observationType): builder.PrependUint8Slot(1, observationType, 0)


def FOBSAddObservation(builder, observation): builder.PrependUOffsetTRelativeSlot(2,
                                                                                  flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                      observation), 0)


def FOBSEnd(builder): return builder.EndObject()
