# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FQuadruple(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFQuadruple(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FQuadruple()
    x.Init(buf, n + offset)
    return x

  # FQuadruple
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FQuadruple
  def Quat(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      x = o + self._tab.Pos
      from .FQuaternion import FQuaternion
      obj = FQuaternion()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FQuadruple
  def XRange(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      x = o + self._tab.Pos
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FQuadruple
  def YRange(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      x = o + self._tab.Pos
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FQuadruple
  def ZRange(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
    if o != 0:
      x = o + self._tab.Pos
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FQuadruple
  def WRange(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
    if o != 0:
      x = o + self._tab.Pos
      from .FRange import FRange
      obj = FRange()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None


def FQuadrupleStart(builder): builder.StartObject(5)


def FQuadrupleAddQuat(builder, quat): builder.PrependStructSlot(0,
                                                                flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                    quat), 0)


def FQuadrupleAddXRange(builder, xRange): builder.PrependStructSlot(1,
                                                                    flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                        xRange), 0)


def FQuadrupleAddYRange(builder, yRange): builder.PrependStructSlot(2,
                                                                    flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                        yRange), 0)


def FQuadrupleAddZRange(builder, zRange): builder.PrependStructSlot(3,
                                                                    flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                        zRange), 0)


def FQuadrupleAddWRange(builder, wRange): builder.PrependStructSlot(4,
                                                                    flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                        wRange), 0)


def FQuadrupleEnd(builder): return builder.EndObject()
