# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FString(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFString(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FString()
    x.Init(buf, n + offset)
    return x

  # FString
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FString
  def Str(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.String(o + self._tab.Pos)
    return bytes()


def FStringStart(builder): builder.StartObject(1)


def FStringAddStr(builder, str): builder.PrependUOffsetTRelativeSlot(0,
                                                                     flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                         str), 0)


def FStringEnd(builder): return builder.EndObject()
