# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers

class FlatBufferPosRotDir(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlatBufferPosRotDir(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatBufferPosRotDir()
        x.Init(buf, n + offset)
        return x

    # FlatBufferPosRotDir
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatBufferPosRotDir
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .FlatBufferVec3 import FlatBufferVec3
            obj = FlatBufferVec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlatBufferPosRotDir
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .FlatBufferVec3 import FlatBufferVec3
            obj = FlatBufferVec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlatBufferPosRotDir
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .FlatBufferVec3 import FlatBufferVec3
            obj = FlatBufferVec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FlatBufferPosRotDirStart(builder): builder.StartObject(3)
def FlatBufferPosRotDirAddPosition(builder, position): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def FlatBufferPosRotDirAddRotation(builder, rotation): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rotation), 0)
def FlatBufferPosRotDirAddDirection(builder, direction): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(direction), 0)
def FlatBufferPosRotDirEnd(builder): return builder.EndObject()
