# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Reaction

import flatbuffers

class FlatBufferConfiguration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlatBufferConfiguration(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatBufferConfiguration()
        x.Init(buf, n + offset)
        return x

    # FlatBufferConfiguration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatBufferConfiguration
    def ConfigurableName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # FlatBufferConfiguration
    def ConfigurableValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FlatBufferConfigurationStart(builder): builder.StartObject(2)
def FlatBufferConfigurationAddConfigurableName(builder, configurableName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(configurableName), 0)
def FlatBufferConfigurationAddConfigurableValue(builder, configurableValue): builder.PrependFloat32Slot(1, configurableValue, 0.0)
def FlatBufferConfigurationEnd(builder): return builder.EndObject()
