# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FByteArray(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFByteArray(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FByteArray()
    x.Init(buf, n + offset)
    return x

  # FByteArray
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FByteArray
  def Bytes(self, j):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      a = self._tab.Vector(o)
      return self._tab.Get(flatbuffers.number_types.Uint8Flags,
                           a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
    return 0

  # FByteArray
  def BytesAsNumpy(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
    return 0

  # FByteArray
  def BytesLength(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.VectorLen(o)
    return 0

  # FByteArray
  def Type(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
    return 0

  # FByteArray
  def Shape(self, j):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      a = self._tab.Vector(o)
      return self._tab.Get(flatbuffers.number_types.Int32Flags,
                           a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
    return 0

  # FByteArray
  def ShapeAsNumpy(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
    return 0

  # FByteArray
  def ShapeLength(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      return self._tab.VectorLen(o)
    return 0


def FByteArrayStart(builder): builder.StartObject(3)


def FByteArrayAddBytes(builder, bytes): builder.PrependUOffsetTRelativeSlot(0,
                                                                            flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                              bytes), 0)


def FByteArrayStartBytesVector(builder, numElems): return builder.StartVector(1, numElems, 1)


def FByteArrayAddType(builder, type): builder.PrependUint8Slot(1, type, 0)


def FByteArrayAddShape(builder, shape): builder.PrependUOffsetTRelativeSlot(2,
                                                                            flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                              shape), 0)


def FByteArrayStartShapeVector(builder, numElems): return builder.StartVector(4, numElems, 4)


def FByteArrayEnd(builder): return builder.EndObject()
