# automatically generated by the FlatBuffers compiler, do not modify

# namespace: State

import flatbuffers


class FSensor(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFSensor(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FSensor()
    x.Init(buf, n + offset)
    return x

  # FSensor
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FSensor
  def SensorName(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.String(o + self._tab.Pos)
    return None

  # FSensor
  def SensorValueType(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
    return 0

  # FSensor
  def SensorValue(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
    if o != 0:
      from flatbuffers.table import Table
      obj = Table(bytearray(), 0)
      self._tab.Union(obj, o)
      return obj
    return None


def FSensorStart(builder): builder.StartObject(3)


def FSensorAddSensorName(builder, sensorName): builder.PrependUOffsetTRelativeSlot(0,
                                                                                   flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                     sensorName), 0)


def FSensorAddSensorValueType(builder, sensorValueType): builder.PrependUint8Slot(1, sensorValueType, 0)


def FSensorAddSensorValue(builder, sensorValue): builder.PrependUOffsetTRelativeSlot(2,
                                                                                     flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                       sensorValue), 0)


def FSensorEnd(builder): return builder.EndObject()
