# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

class FSimulationType(object):
  Independent = 0
  FrameDependent = 1
  PhysicsDependent = 2
  EventDependent = 3
