# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FValuedVector3s(object):
  __slots__ = ['_tab']

  @classmethod
  def GetRootAsFValuedVector3s(cls, buf, offset):
    n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
    x = FValuedVector3s()
    x.Init(buf, n + offset)
    return x

  # FValuedVector3s
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FValuedVector3s
  def Vals(self, j):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      a = self._tab.Vector(o)
      return self._tab.Get(flatbuffers.number_types.Float64Flags,
                           a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
    return 0

  # FValuedVector3s
  def ValsAsNumpy(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
    return 0

  # FValuedVector3s
  def ValsLength(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
    if o != 0:
      return self._tab.VectorLen(o)
    return 0

  # FValuedVector3s
  def Points(self, j):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      x = self._tab.Vector(o)
      x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
      from .FVector3 import FVector3
      obj = FVector3()
      obj.Init(self._tab.Bytes, x)
      return obj
    return None

  # FValuedVector3s
  def PointsLength(self):
    o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
    if o != 0:
      return self._tab.VectorLen(o)
    return 0


def FValuedVector3sStart(builder): builder.StartObject(2)


def FValuedVector3sAddVals(builder, vals): builder.PrependUOffsetTRelativeSlot(0,
                                                                               flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                 vals), 0)


def FValuedVector3sStartValsVector(builder, numElems): return builder.StartVector(8, numElems, 8)


def FValuedVector3sAddPoints(builder, points): builder.PrependUOffsetTRelativeSlot(1,
                                                                                   flatbuffers.number_types.UOffsetTFlags.py_type(
                                                                                     points), 0)


def FValuedVector3sStartPointsVector(builder, numElems): return builder.StartVector(24, numElems, 8)


def FValuedVector3sEnd(builder): return builder.EndObject()
