# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FVector2(object):
  __slots__ = ['_tab']

  # FVector2
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FVector2
  def X(self): return self._tab.Get(flatbuffers.number_types.Float64Flags,
                                    self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

  # FVector2
  def Y(self): return self._tab.Get(flatbuffers.number_types.Float64Flags,
                                    self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))


def CreateFVector2(builder, x, y):
  builder.Prep(8, 16)
  builder.PrependFloat64(y)
  builder.PrependFloat64(x)
  return builder.Offset()
