# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBS

import flatbuffers


class FVector3(object):
  __slots__ = ['_tab']

  # FVector3
  def Init(self, buf, pos):
    self._tab = flatbuffers.table.Table(buf, pos)

  # FVector3
  def X(self): return self._tab.Get(flatbuffers.number_types.Float64Flags,
                                    self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

  # FVector3
  def Y(self): return self._tab.Get(flatbuffers.number_types.Float64Flags,
                                    self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

  # FVector3
  def Z(self): return self._tab.Get(flatbuffers.number_types.Float64Flags,
                                    self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))


def CreateFVector3(builder, x, y, z):
  builder.Prep(8, 24)
  builder.PrependFloat64(z)
  builder.PrependFloat64(y)
  builder.PrependFloat64(x)
  return builder.Offset()
